name: 🧪 Unit Test
description: Run Unit Tests

inputs:
  workingDirectory:
    required: true
    description: Working directory where the tests will run.

runs:
  using: composite
  steps:
  - name: Install Packages
    shell: bash
    run : npm install
    working-directory: ${{ inputs.workingDirectory }}

  - name: Test
    shell: bash
    run: npm test
    working-directory: ${{ inputs.workingDirectory }}
