name: 🧹 Prettier
description: Run Prettier

inputs:
  workingDirectory:
    required: true
    description: Working directory where the tests will run.

runs:
  using: composite
  steps:
  - name: Install Packages
    shell: bash
    run : yarn install
    working-directory: ${{ inputs.workingDirectory }}

  - name: Prettier
    shell: bash
    run: yarn prettier:check
    working-directory: ${{ inputs.workingDirectory }}
