version: '3'
services:
  api:
    image: lol-scout-app
    build: .
    # networks:
    #   - backend
    ports:
      - "8080:8080"

  # web-cli:
  #  image: lol-scout-app
  #   networks:
  #     - backend
  #   command: sh

  # networks:
  #   backend:
  #     driver: bridge