name: Terraform
description: create the infrastructure.

inputs:
  workingDirectory:
    required: true
    description: Working directory where terraform will run.

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform init
      shell: bash
      run: terraform init
      working-directory: ${{inputs.workingDirectory}}

    - name: Terraform Apply
      shell: bash
      run: terraform apply -auto-approve
      working-directory: ${{inputs.workingDirectory}}
