const { createSpyFromClass } = require("jasmine-auto-spies")
const { MatchesController } = require("../src/controllers/matches")
const { RiotApi } = require("../src/services/riotApi")

describe('MatchesController', () => {
    const mockRiotApi = createSpyFromClass(RiotApi)
    const fakeMatchId = 'fakeMatchId'
    let summoner

    const mockParticpants = [
        {
        "assists": 7,
        "baronKills": 0,
        "basicPings": 16,
        "bountyLevel": 3,
        "challenges": {
            "12AssistStreakCount": 0,
            "abilityUses": 74,
            "acesBefore15Minutes": 0,
            "alliedJungleMonsterKills": 0,
            "baronTakedowns": 0,
            "blastConeOppositeOpponentCount": 0,
            "bountyGold": 0,
            "buffsStolen": 1,
            "completeSupportQuestInTime": 0,
            "controlWardTimeCoverageInRiverOrEnemyHalf": 0.07794208727521494,
            "controlWardsPlaced": 1,
            "damagePerMinute": 669.3269116571229,
            "damageTakenOnTeamPercentage": 0.20031007909079462,
            "dancedWithRiftHerald": 0,
            "deathsByEnemyChamps": 2,
            "dodgeSkillShotsSmallWindow": 0,
            "doubleAces": 0,
            "dragonTakedowns": 1,
            "earliestDragonTakedown": 1297.4885922879098,
            "earlyLaningPhaseGoldExpAdvantage": 1,
            "effectiveHealAndShielding": 0,
            "elderDragonKillsWithOpposingSoul": 0,
            "elderDragonMultikills": 0,
            "enemyChampionImmobilizations": 36,
            "enemyJungleMonsterKills": 9.500000029802322,
            "epicMonsterKillsNearEnemyJungler": 0,
            "epicMonsterKillsWithin30SecondsOfSpawn": 0,
            "epicMonsterSteals": 0,
            "epicMonsterStolenWithoutSmite": 0,
            "firstTurretKilledTime": 830.3246445128291,
            "flawlessAces": 0,
            "fullTeamTakedown": 0,
            "gameLength": 1388.6382760986792,
            "getTakedownsInAllLanesEarlyJungleAsLaner": 0,
            "goldPerMinute": 476.22506656424366,
            "hadOpenNexus": 0,
            "immobilizeAndKillWithAlly": 5,
            "initialBuffCount": 0,
            "initialCrabCount": 0,
            "jungleCsBefore10Minutes": 0,
            "junglerTakedownsNearDamagedEpicMonster": 0,
            "kTurretsDestroyedBeforePlatesFall": 1,
            "kda": 7.5,
            "killAfterHiddenWithAlly": 1,
            "killParticipation": 0.3409090909090909,
            "killedChampTookFullTeamDamageSurvived": 0,
            "killingSprees": 2,
            "killsNearEnemyTurret": 3,
            "killsOnOtherLanesEarlyJungleAsLaner": 0,
            "killsOnRecentlyHealedByAramPack": 0,
            "killsUnderOwnTurret": 1,
            "killsWithHelpFromEpicMonster": 0,
            "knockEnemyIntoTeamAndKill": 9,
            "landSkillShotsEarlyGame": 0,
            "laneMinionsFirst10Minutes": 79,
            "laningPhaseGoldExpAdvantage": 1,
            "legendaryCount": 0,
            "lostAnInhibitor": 0,
            "maxCsAdvantageOnLaneOpponent": 51,
            "maxKillDeficit": 1,
            "maxLevelLeadLaneOpponent": 3,
            "moreEnemyJungleThanOpponent": -97.00000008940697,
            "multiKillOneSpell": 0,
            "multiTurretRiftHeraldCount": 0,
            "multikills": 1,
            "multikillsAfterAggressiveFlash": 0,
            "mythicItemUsed": 6631,
            "outerTurretExecutesBefore10Minutes": 0,
            "outnumberedKills": 4,
            "outnumberedNexusKill": 0,
            "perfectDragonSoulsTaken": 0,
            "perfectGame": 0,
            "pickKillWithAlly": 9,
            "playedChampSelectPosition": 1,
            "poroExplosions": 0,
            "quickCleanse": 0,
            "quickFirstTurret": 0,
            "quickSoloKills": 0,
            "riftHeraldTakedowns": 0,
            "saveAllyFromDeath": 0,
            "scuttleCrabKills": 0,
            "shortestTimeToAceFromFirstTakedown": 17.87930105738542,
            "skillshotsDodged": 9,
            "skillshotsHit": 0,
            "snowballsHit": 0,
            "soloBaronKills": 0,
            "soloKills": 5,
            "stealthWardsPlaced": 5,
            "survivedSingleDigitHpCount": 0,
            "survivedThreeImmobilizesInFight": 4,
            "takedownOnFirstTurret": 1,
            "takedowns": 15,
            "takedownsAfterGainingLevelAdvantage": 0,
            "takedownsBeforeJungleMinionSpawn": 0,
            "takedownsFirstXMinutes": 5,
            "takedownsInAlcove": 0,
            "takedownsInEnemyFountain": 0,
            "teamBaronKills": 0,
            "teamDamagePercentage": 0.20976463071518572,
            "teamElderDragonKills": 0,
            "teamRiftHeraldKills": 1,
            "threeWardsOneSweeperCount": 0,
            "tookLargeDamageSurvived": 0,
            "turretPlatesTaken": 5,
            "turretTakedowns": 2,
            "turretsTakenWithRiftHerald": 0,
            "twentyMinionsIn3SecondsCount": 6,
            "unseenRecalls": 0,
            "visionScoreAdvantageLaneOpponent": -0.5919978618621826,
            "visionScorePerMinute": 0.44401221801595864,
            "wardTakedowns": 0,
            "wardTakedownsBefore20M": 0,
            "wardsGuarded": 0
        },
        "champExperience": 11831,
        "champLevel": 14,
        "championId": 875,
        "championName": "Sett",
        "championTransform": 0,
        "consumablesPurchased": 3,
        "damageDealtToBuildings": 3931,
        "damageDealtToObjectives": 5970,
        "damageDealtToTurrets": 3931,
        "damageSelfMitigated": 15322,
        "deaths": 2,
        "detectorWardsPlaced": 1,
        "doubleKills": 1,
        "dragonKills": 0,
        "eligibleForProgression": true,
        "firstBloodAssist": false,
        "firstBloodKill": false,
        "firstTowerAssist": false,
        "firstTowerKill": false,
        "gameEndedInEarlySurrender": false,
        "gameEndedInSurrender": false,
        "goldEarned": 11021,
        "goldSpent": 10250,
        "individualPosition": "TOP",
        "inhibitorKills": 0,
        "inhibitorTakedowns": 1,
        "inhibitorsLost": 0,
        "item0": 3153,
        "item1": 6631,
        "item2": 2055,
        "item3": 1031,
        "item4": 3047,
        "item5": 3133,
        "item6": 3340,
        "itemsPurchased": 21,
        "killingSprees": 2,
        "kills": 8,
        "lane": "TOP",
        "largestCriticalStrike": 0,
        "largestKillingSpree": 4,
        "largestMultiKill": 2,
        "longestTimeSpentLiving": 909,
        "magicDamageDealt": 167,
        "magicDamageDealtToChampions": 167,
        "magicDamageTaken": 4742,
        "neutralMinionsKilled": 12,
        "nexusKills": 1,
        "nexusLost": 0,
        "nexusTakedowns": 1,
        "objectivesStolen": 0,
        "objectivesStolenAssists": 0,
        "participantId": 1,
        "pentaKills": 0,
        "perks": {
            "statPerks": {
                "defense": 5002,
                "flex": 5008,
                "offense": 5005
            },
            "styles": [
                {
                    "description": "primaryStyle",
                    "selections": [
                        {
                            "perk": 8010,
                            "var1": 275,
                            "var2": 0,
                            "var3": 0
                        },
                        {
                            "perk": 9111,
                            "var1": 1465,
                            "var2": 300,
                            "var3": 0
                        },
                        {
                            "perk": 9104,
                            "var1": 14,
                            "var2": 50,
                            "var3": 0
                        },
                        {
                            "perk": 8299,
                            "var1": 640,
                            "var2": 0,
                            "var3": 0
                        }
                    ],
                    "style": 8000
                },
                {
                    "description": "subStyle",
                    "selections": [
                        {
                            "perk": 8444,
                            "var1": 867,
                            "var2": 0,
                            "var3": 0
                        },
                        {
                            "perk": 8451,
                            "var1": 162,
                            "var2": 0,
                            "var3": 0
                        }
                    ],
                    "style": 8400
                }
            ]
        },
        "physicalDamageDealt": 78051,
        "physicalDamageDealtToChampions": 11924,
        "physicalDamageTaken": 10422,
        "profileIcon": 3798,
        "puuid": "_JHispJI4GSjEK5c1dz73qxNHC64yeuaEaUNC2C3d5gUYjXnwT6b7JPjtjmE2AyAbcJwo_IpPOGxsQ",
        "quadraKills": 0,
        "riotIdName": "",
        "riotIdTagline": "",
        "role": "SOLO",
        "sightWardsBoughtInGame": 0,
        "spell1Casts": 41,
        "spell2Casts": 16,
        "spell3Casts": 13,
        "spell4Casts": 4,
        "summoner1Casts": 2,
        "summoner1Id": 4,
        "summoner2Casts": 5,
        "summoner2Id": 14,
        "summonerId": "2ogQClag8rrvUt3TeW03_EmO9NSNe2rSJKWWzyn1K71XtQI",
        "summonerLevel": 96,
        "summonerName": "mar6ix",
        "teamEarlySurrendered": false,
        "teamId": 100,
        "teamPosition": "TOP",
        "timeCCingOthers": 16,
        "timePlayed": 1388,
        "totalDamageDealt": 89929,
        "totalDamageDealtToChampions": 15490,
        "totalDamageShieldedOnTeammates": 0,
        "totalDamageTaken": 16520,
        "totalHeal": 1943,
        "totalHealsOnTeammates": 0,
        "totalMinionsKilled": 136,
        "totalTimeCCDealt": 84,
        "totalTimeSpentDead": 73,
        "totalUnitsHealed": 1,
        "tripleKills": 0,
        "trueDamageDealt": 11709,
        "trueDamageDealtToChampions": 3398,
        "trueDamageTaken": 1355,
        "turretKills": 2,
        "turretTakedowns": 2,
        "turretsLost": 1,
        "unrealKills": 0,
        "visionScore": 10,
        "visionWardsBoughtInGame": 2,
        "wardsKilled": 0,
        "wardsPlaced": 6,
        "win": true
    },
    {
        "assists": 7,
        "baronKills": 0,
        "basicPings": 26,
        "bountyLevel": 2,
        "challenges": {
            "12AssistStreakCount": 0,
            "abilityUses": 231,
            "acesBefore15Minutes": 0,
            "alliedJungleMonsterKills": 85.60000011324883,
            "baronTakedowns": 0,
            "blastConeOppositeOpponentCount": 0,
            "bountyGold": 0,
            "buffsStolen": 0,
            "completeSupportQuestInTime": 0,
            "controlWardsPlaced": 0,
            "damagePerMinute": 154.9778425142639,
            "damageTakenOnTeamPercentage": 0.20907192459966234,
            "dancedWithRiftHerald": 0,
            "deathsByEnemyChamps": 1,
            "dodgeSkillShotsSmallWindow": 4,
            "doubleAces": 0,
            "dragonTakedowns": 2,
            "earliestDragonTakedown": 607.4971699780843,
            "earlyLaningPhaseGoldExpAdvantage": 0,
            "effectiveHealAndShielding": 0,
            "elderDragonKillsWithOpposingSoul": 0,
            "elderDragonMultikills": 0,
            "enemyChampionImmobilizations": 11,
            "enemyJungleMonsterKills": 5.5,
            "epicMonsterKillsNearEnemyJungler": 0,
            "epicMonsterKillsWithin30SecondsOfSpawn": 0,
            "epicMonsterSteals": 0,
            "epicMonsterStolenWithoutSmite": 0,
            "firstTurretKilledTime": 830.3246445128291,
            "flawlessAces": 0,
            "fullTeamTakedown": 0,
            "gameLength": 1388.6382760986792,
            "goldPerMinute": 429.64052173015534,
            "hadOpenNexus": 0,
            "immobilizeAndKillWithAlly": 9,
            "initialBuffCount": 2,
            "initialCrabCount": 0,
            "jungleCsBefore10Minutes": 43.60000005364418,
            "junglerKillsEarlyJungle": 0,
            "junglerTakedownsNearDamagedEpicMonster": 0,
            "kTurretsDestroyedBeforePlatesFall": 0,
            "kda": 11,
            "killAfterHiddenWithAlly": 1,
            "killParticipation": 0.25,
            "killedChampTookFullTeamDamageSurvived": 0,
            "killsNearEnemyTurret": 0,
            "killsOnLanersEarlyJungleAsJungler": 1,
            "killsOnRecentlyHealedByAramPack": 0,
            "killsUnderOwnTurret": 0,
            "killsWithHelpFromEpicMonster": 0,
            "knockEnemyIntoTeamAndKill": 0,
            "landSkillShotsEarlyGame": 0,
            "laneMinionsFirst10Minutes": 2,
            "laningPhaseGoldExpAdvantage": 0,
            "legendaryCount": 0,
            "lostAnInhibitor": 0,
            "maxCsAdvantageOnLaneOpponent": 32.60000002384186,
            "maxKillDeficit": 1,
            "maxLevelLeadLaneOpponent": 2,
            "moreEnemyJungleThanOpponent": -53.40000003576279,
            "multiKillOneSpell": 0,
            "multiTurretRiftHeraldCount": 0,
            "multikills": 0,
            "multikillsAfterAggressiveFlash": 0,
            "mythicItemUsed": 3078,
            "outerTurretExecutesBefore10Minutes": 0,
            "outnumberedKills": 1,
            "outnumberedNexusKill": 0,
            "perfectDragonSoulsTaken": 0,
            "perfectGame": 0,
            "pickKillWithAlly": 8,
            "playedChampSelectPosition": 1,
            "poroExplosions": 0,
            "quickCleanse": 0,
            "quickFirstTurret": 0,
            "quickSoloKills": 0,
            "riftHeraldTakedowns": 1,
            "saveAllyFromDeath": 0,
            "scuttleCrabKills": 1,
            "shortestTimeToAceFromFirstTakedown": 15.85578197673874,
            "skillshotsDodged": 22,
            "skillshotsHit": 0,
            "snowballsHit": 0,
            "soloBaronKills": 0,
            "soloKills": 0,
            "soloTurretsLategame": 2,
            "stealthWardsPlaced": 0,
            "survivedSingleDigitHpCount": 0,
            "survivedThreeImmobilizesInFight": 0,
            "takedownOnFirstTurret": 0,
            "takedowns": 11,
            "takedownsAfterGainingLevelAdvantage": 1,
            "takedownsBeforeJungleMinionSpawn": 0,
            "takedownsFirstXMinutes": 6,
            "takedownsInAlcove": 0,
            "takedownsInEnemyFountain": 0,
            "teamBaronKills": 0,
            "teamDamagePercentage": 0.04856949472352031,
            "teamElderDragonKills": 0,
            "teamRiftHeraldKills": 1,
            "threeWardsOneSweeperCount": 0,
            "tookLargeDamageSurvived": 0,
            "turretPlatesTaken": 0,
            "turretTakedowns": 3,
            "turretsTakenWithRiftHerald": 0,
            "twentyMinionsIn3SecondsCount": 0,
            "unseenRecalls": 0,
            "visionScoreAdvantageLaneOpponent": -0.4260808825492859,
            "visionScorePerMinute": 0.3525035842002364,
            "wardTakedowns": 1,
            "wardTakedownsBefore20M": 1,
            "wardsGuarded": 0
        },
        "champExperience": 11070,
        "champLevel": 13,
        "championId": 24,
        "championName": "Jax",
        "championTransform": 0,
        "consumablesPurchased": 3,
        "damageDealtToBuildings": 5438,
        "damageDealtToObjectives": 35496,
        "damageDealtToTurrets": 5438,
        "damageSelfMitigated": 11074,
        "deaths": 1,
        "detectorWardsPlaced": 0,
        "doubleKills": 0,
        "dragonKills": 2,
        "eligibleForProgression": true,
        "firstBloodAssist": false,
        "firstBloodKill": false,
        "firstTowerAssist": false,
        "firstTowerKill": false,
        "gameEndedInEarlySurrender": false,
        "gameEndedInSurrender": false,
        "goldEarned": 9943,
        "goldSpent": 5983,
        "individualPosition": "JUNGLE",
        "inhibitorKills": 1,
        "inhibitorTakedowns": 1,
        "inhibitorsLost": 0,
        "item0": 3078,
        "item1": 2031,
        "item2": 1001,
        "item3": 1042,
        "item4": 3133,
        "item5": 1042,
        "item6": 3364,
        "itemsPurchased": 14,
        "killingSprees": 2,
        "kills": 4,
        "lane": "JUNGLE",
        "largestCriticalStrike": 0,
        "largestKillingSpree": 2,
        "largestMultiKill": 1,
        "longestTimeSpentLiving": 990,
        "magicDamageDealt": 31548,
        "magicDamageDealtToChampions": 632,
        "magicDamageTaken": 3230,
        "neutralMinionsKilled": 119,
        "nexusKills": 0,
        "nexusLost": 0,
        "nexusTakedowns": 0,
        "objectivesStolen": 0,
        "objectivesStolenAssists": 0,
        "participantId": 2,
        "pentaKills": 0,
        "perks": {
            "statPerks": {
                "defense": 5002,
                "flex": 5002,
                "offense": 5005
            },
            "styles": [
                {
                    "description": "primaryStyle",
                    "selections": [
                        {
                            "perk": 8010,
                            "var1": 0,
                            "var2": 0,
                            "var3": 0
                        },
                        {
                            "perk": 9111,
                            "var1": 258,
                            "var2": 220,
                            "var3": 0
                        },
                        {
                            "perk": 9103,
                            "var1": 16,
                            "var2": 30,
                            "var3": 0
                        },
                        {
                            "perk": 8014,
                            "var1": 176,
                            "var2": 0,
                            "var3": 0
                        }
                    ],
                    "style": 8000
                },
                {
                    "description": "subStyle",
                    "selections": [
                        {
                            "perk": 8143,
                            "var1": 142,
                            "var2": 0,
                            "var3": 0
                        },
                        {
                            "perk": 8138,
                            "var1": 18,
                            "var2": 0,
                            "var3": 0
                        }
                    ],
                    "style": 8100
                }
            ]
        },
        "physicalDamageDealt": 100866,
        "physicalDamageDealtToChampions": 2852,
        "physicalDamageTaken": 13902,
        "profileIcon": 28,
        "puuid": "a5V_5f6XY5NX54d0tSOfJmDmS92oelvlsTlYE9duy7LGmOzljDkskWvjT_V-ZJvh2l8tM2iZ7totPg",
        "quadraKills": 0,
        "riotIdName": "",
        "riotIdTagline": "",
        "role": "NONE",
        "sightWardsBoughtInGame": 0,
        "spell1Casts": 61,
        "spell2Casts": 117,
        "spell3Casts": 50,
        "spell4Casts": 3,
        "summoner1Casts": 4,
        "summoner1Id": 4,
        "summoner2Casts": 14,
        "summoner2Id": 11,
        "summonerId": "2m4AniUGxFkUhBYkJWfxLF2igvZXZIzKMIf_uQrdRo6aA4g",
        "summonerLevel": 85,
        "summonerName": "Aatrox I Mid ",
        "teamEarlySurrendered": false,
        "teamId": 100,
        "teamPosition": "JUNGLE",
        "timeCCingOthers": 9,
        "timePlayed": 1388,
        "totalDamageDealt": 149340,
        "totalDamageDealtToChampions": 3586,
        "totalDamageShieldedOnTeammates": 0,
        "totalDamageTaken": 17243,
        "totalHeal": 6465,
        "totalHealsOnTeammates": 0,
        "totalMinionsKilled": 26,
        "totalTimeCCDealt": 227,
        "totalTimeSpentDead": 32,
        "totalUnitsHealed": 1,
        "tripleKills": 0,
        "trueDamageDealt": 16925,
        "trueDamageDealtToChampions": 102,
        "trueDamageTaken": 110,
        "turretKills": 3,
        "turretTakedowns": 3,
        "turretsLost": 1,
        "unrealKills": 0,
        "visionScore": 8,
        "visionWardsBoughtInGame": 0,
        "wardsKilled": 1,
        "wardsPlaced": 0,
        "win": true
    }]

    beforeAll(() => {
        match = new MatchesController(mockRiotApi)
    })

    describe('getPlayerMatchHistory', () => {
        it('should return the correct participant data', async () => {
            mockRiotApi.getMatchParticipants.and.returnValue(mockParticpants)
            const fakeParticipant = mockParticpants[1]
            const result = await match.getPlayerMatchHistory(fakeMatchId, fakeParticipant.puuid)

            const kda = (fakeParticipant.kills + fakeParticipant.assists)/fakeParticipant.deaths
            const Time = fakeParticipant.timePlayed/60
            const expectedTime = Math.ceil(Time * 100) / 100;
            const expectedKDA = Math.ceil(kda * 100) / 100;
            const expected = {
                puuid: fakeParticipant.puuid,
                championId: fakeParticipant.championId,
                kills: fakeParticipant.kills,
                deaths: fakeParticipant.deaths,
                assists: fakeParticipant.assists,
                KDA: expectedKDA,
                time: expectedTime
            }
            expect(result).toEqual(expected)
        })

        it('should return an error message if no player history is found', async () => {
            mockRiotApi.getMatchParticipants.and.returnValue(mockParticpants)
            const nonexistantPlayerId = 'I do not exist'
            const result = await match.getPlayerMatchHistory(fakeMatchId, nonexistantPlayerId)
            expect(result).toEqual(`PUUID: ${nonexistantPlayerId} does not exist for match: ${fakeMatchId}`)
        })
    })
})