name: DEV - CI
description: Continuous integration for the dev environment

on:
  push:

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v3

    - uses: '../actions/tests'
      with:
        workingDirectory: ./