name: DEV - CI

on:
  push:

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v3

    - name: NPM Install
      shell: bash
      run : npm install

    # TODO
      # - name: Lint
      #   shell: bash
      #   run: yarn run lint

    - name: Unit Test
      shell: bash
      run: npm test