name: DEV - CI

on:
  workflow_dispatch:

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          workingDirectory: api

  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZUIRE_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZUIRE_TENANT_ID}}
      environment: dev

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: './infrastructure'
        env:
          TF_VAR_environment: 'dev'

      - name: Terraform Format
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: 'fmt -check'
          tf_actions_working_dir: './infrastructure'
        env:
          TF_VAR_environment: 'dev'

      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: './infrastructure'
        env:
          TF_VAR_environment: 'dev'

      - name: Terraform Apply
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: 'apply -auto-approve'
          tf_actions_working_dir: './infrastructure'
        env:
          TF_VAR_environment: 'dev'
