name: TEST - CI

on: 
  push:
    branches:
      - main

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - uses: actions/checkout@v3

    - name: NPM Install
      shell: bash
      run : |
        cd api
        npm install

    # TODO
      # - name: Lint
      #   shell: bash
      #   run: yarn run lint

    - name: Unit Test
      shell: bash
      run: |
        cd api
        npm test