name: 📊 Update Stat Data

on:
  push:
    branches: 
    - story/google-spreadsheet-pipeline

jobs:
  get-data:
    name: 📊 Get Data from Spreadsheet
    runs-on: ubuntu-latest
    env:
      GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL}}
      GOOGLE_PRIVATE_KEY: ${{secrets.GOOGLE_PRIVATE_KEY}}
      SPREADSHEET_ID: ${{secrets.SPREADSHEET_ID}}

    steps:
      - uses: actions/checkout@v3

      - name: Install Packages
        shell: bash
        run : yarn install
        working-directory: ./web
      
      - name: Run Script
        shell: bash
        run : yarn get:data
        working-directory: ./web
    
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Commit and Push
        shell: bash
        run: |
          git config user.name "RedPandaBot"
          git config user.email "<>"
          git switch -c update-data-${{ steps.date.outputs.date }}
          git add ./web/data/teams.json
          git commit -m "update spreadsheet data"
          
